services:
  - type: web
    name: fake-job-backend
    env: node
    rootDir: server
    buildCommand: npm run build && npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: ML_SERVICE_URL
        fromService:
          name: fake-job-ml
          type: web
          property: host

  # Python ML Service
  - type: web
    name: fake-job-ml
    env: python
    rootDir: ml-service
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --port=$PORT app:app
    envVars:
      - key: PORT
        value: 5000

